### ISSUE TITLE
Cannot run image, issues with touching docker.ini

### ISSUE THREAD

**Issue by chanibal** [karasevm/couchdb-raspberry-pi#1]
Hello, I don't know docker to well, but I guess this should work:

```bash
$ docker run -d --name my-couchdb -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=pppassword karasevm/couchdb
cb564b12e06d3dc59301e141286f47de3c44d9cb8c92f5b36a84236e48ab6eaa

$ docker logs my-couchdb
touch: setting times of '/opt/couchdb/etc/local.d/docker.ini': Operation not permitted

$ docker ps | grep --ignore-case --count couch
0
```

Not sure how to continue with this issue, there are mentions of something simillar on the apache/couchdb-docker github, but they are quite unhelpfull. 

- Raspbian GNU/Linux 10 (buster)
- Docker version 19.03.13, build 4484c46
- Linux pi3 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux (raspberry pi 3)

Any help would be welcome, I need to run couchdb on this raspberry - so if you have a reliable .deb of couchdb in ARM architecture this will fix my case also.

**Comment by karasevm** [comment]
Hi, sadly I'm unable to replicate on bullseye with docker 27.2.1, but from a bit of research it seems that [updating to docker 20.10.10 or higher may fix this](https://docs.linuxserver.io/FAQ/#resolution) (there's also a workaround described there in case you can't update).    

Also, depending on your environment and use case, you should consider updating the OS:
- [Buster has been EOL for couple of months already](https://lists.debian.org/debian-lts-announce/2024/05/msg00002.html), you won't receive any package updates from the official repos
- Your board supports the 64 bit version of Raspberry Pi OS, on which you will be able to use the official CouchDB arm64 packages

**Comment by chanibal** [comment]
Thanks for checking this. I can't switch to 64 bit because this is a way to remote PI for me to be able to re-image the SD card (and doing that online while possible seems very risky). So yes, a system upgrade is long overdue - didn't think this might have caused the issue.

Thanks again!
