### ISSUE TITLE
libmozjs-78.so missing

### ISSUE THREAD

**Issue by Vali-98** [karasevm/couchdb-raspberry-pi#2]
Hey there, just to preface this, I'm new to docker and I have already resolved the issue on my side.

I was trying to use this image on my Pi 3B+ running raspbian (bullseye), but it seemed like `libmozjs-78.so` was missing from the container's libraries. I had to docker exec bash to run apt-get update and install said package.

This issue is also a bit sneaky, since the container will start up without issue but will log errors. Using the `Verify Installation` function in couchdb, it will fail on CreateView.

Is the current docker-hub image malformed? Or was there an issue with my setup?

Edit: It seems this package was removed on this commit:

https://github.com/karasevm/couchdb-raspberry-pi/commit/242dce61c9411037e8967989c7a08f1d6ad2ed93#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L32

Was this on purpose?

**Comment by karasevm** [comment]
Great catch, I wasn't aware of Fauxton's verification feature and in my use case everything seemed to work fine.

**Comment by Vali-98** [comment]
Thanks for the update, I think the PR fixes the issue properly. Resolved.
